# Generated by Django 5.2.8 on 2026-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_seed_demo_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
