# Generated by Django 5.2.4 on 2025-07-27 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeblock',
            old_name='code_template',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='codeblock',
            name='hints',
        ),
        migrations.RemoveField(
            model_name='codeblock',
            name='simulation_note',
        ),
        migrations.RemoveField(
            model_name='codeblock',
            name='system',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='xp',
        ),
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
        migrations.RemoveField(
            model_name='level',
            name='total_systems',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='system',
            name='badge_name',
        ),
        migrations.RemoveField(
            model_name='system',
            name='build_videos',
        ),
        migrations.RemoveField(
            model_name='system',
            name='intro_story',
        ),
        migrations.RemoveField(
            model_name='system',
            name='required_xp',
        ),
        migrations.AddField(
            model_name='codeblock',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='code_blocks', to='levels.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codeblock',
            name='title',
            field=models.CharField(default='Placeholder CodeBlock', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='badge_name',
            field=models.CharField(default='Default Badge', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='required_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='system',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/images/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_b',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option_c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='system',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
