# Generated by Django 5.2.8 on 2026-01-13 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_rename_code_template_codeblock_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('card_type', models.CharField(choices=[('intro', 'Intro'), ('visual', 'Visual'), ('action', 'Action'), ('quiz', 'Quiz'), ('code', 'Code'), ('reward', 'Reward')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('youtube_id', models.CharField(blank=True, max_length=64)),
                ('question', models.CharField(blank=True, max_length=500)),
                ('choice_a', models.CharField(blank=True, max_length=255)),
                ('choice_b', models.CharField(blank=True, max_length=255)),
                ('choice_c', models.CharField(blank=True, max_length=255)),
                ('correct_choice', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('action_label', models.CharField(blank=True, max_length=255)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('starter_code', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='levels.lesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
    ]
