# Generated by Django 5.2.8 on 2026-01-13 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_seed_m2_lesson1_cards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('mission_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('mission_complete', 'Mission Complete'), ('xp_total', 'XP Total'), ('step_count', 'Step Count')], default='mission_complete', max_length=32)),
                ('rule_value', models.PositiveIntegerField(default=0)),
                ('xp_threshold', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_number', models.PositiveSmallIntegerField(choices=[(1, 'Mission 1'), (2, 'Mission 2'), (3, 'Mission 3'), (4, 'Mission 4')])),
                ('group_slug', models.SlugField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('content_mode', models.CharField(choices=[('video', 'Video'), ('cards', 'Cards'), ('info', 'Info')], default='info', max_length=16)),
                ('is_quiz', models.BooleanField(default=False)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
            ],
            options={
                'ordering': ['mission_number', 'order'],
                'unique_together': {('mission_number', 'group_slug', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='levels.badge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('badge', 'session_key'), ('badge', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='levels.step')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('step', 'session_key'), ('step', 'user')},
            },
        ),
    ]
