# Generated by Django 5.2.8 on 2026-01-13 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('rule_type', models.CharField(max_length=100)),
                ('rule_target', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('parent_slug', models.SlugField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('content_mode', models.CharField(choices=[('video', 'Video'), ('cards', 'Cards')], max_length=10)),
                ('has_quiz', models.BooleanField(default=False)),
                ('youtube_id', models.CharField(blank=True, max_length=50)),
                ('xp_on_complete', models.PositiveIntegerField(default=0)),
                ('xp_on_quiz_correct', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['parent_slug', 'order'],
                'unique_together': {('slug', 'parent_slug')},
            },
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_badge_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='StepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('quiz_passed', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_step_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'step')},
            },
        ),
    ]
